[package]
name = "solar_model"
version = "0.1.0"
authors = ["German Molina <germolinal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calendar = { path = "../../calendar" }
weather = {path = "../../weather"}
building_model = {path = "../../building_model"}
communication_protocols = { path = "../../communication_protocols" }